### PR TITLE
VLM support

### PR DESCRIPTION
**Pull request by Raniz85**

### CODE REVIEW

**Comment by Raniz85** [comment]
I needed these so thought I might as well contribute them back. Would be nice if we could get a release to crates.io with these changes and `Instance::with_args`

**Comment by garkimasera** [comment]
Thank you for your PR. I think that vlm APIs should be separated from core module. Like [`MediaPlayerAudioEx`](https://docs.rs/vlc-rs/0.3.0/vlc/trait.MediaPlayerAudioEx.html), new trait and module are needed. For example,
```
// in vlm.rs
trait Vlm {
    fn add_broadcast(&self, ...);
    ...
}

impl Vlm for Instance {
    fn add_broadcast(&self, ...) { ... }
    ...
}
```

**Comment by Raniz85** [comment]
I'll refactor it like that

**Comment by Raniz85** [comment]
Refactored into a trait and added some more methods as well as support for events (which requires _Instance_ to be _Send_ to be useful, hence the pull from 0xpr03)

**Comment by garkimasera** [comment]
Thanks!

**Pull request merged**
